# Generated by Django 5.0.3 on 2024-05-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloAutenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
